### ISSUE TITLE
Error When trying to train model

### ISSUE THREAD

**Issue by roxqtang** [SDret/Pytorch-implementation-for-Rethinking-Reconstruction-Autoencoder-Based-Out-of-Distribution-Detection#1]
Hi, I have followed your instruction and downloaded cifar100 to a newly created "data" file under the main directory, but when I try to run train with cifar100, it tells me " No such file or directory: '/home/zyb/playground/OoD/data/cifar100/dataset.pkl'
", I am not sure what am I suppose to do. I could create a file called dataset.pkl but I don't know what did you save in the dataset.pkl file. So do you have a solution for this? Thank you before hands!

**Comment by SDret** [comment]
Hi, the script to make this pickle file is './dataset/ood/preprocess/format_cifar100.py''.

**Comment by roxqtang** [comment]
> Hi, the script to make this pickle file is './dataset/ood/preprocess/format_cifar100.py''.

Thank you for the help, I see it now!
